### PR TITLE
Update QR scanner screen #1814

### LINKED ISSUE #1814: Update QR scanner screen
We currently use a fork (see Podfile) of QRCodeReaderViewController. Can you either modify it or implement it so that it looks like this? It's fine (probably best) if you can remove the dependency on QRCodeReaderViewController if implementing the scanner from scratch works for you:

https://app.zeplin.io/project/5d0356be2f25b319dcc5944b/screen/5e54e153f1689c658669eb8a

It's probably used in a few places.

Out of scope
---
You can ignore the "My QR code" button for now.

---

Boon for later:

- [x] ~~Create issue, add "My QR code" button~~ #1826

Related: #1738

### PR DESCRIPTION
**Pull request by vladyslav-iosdev**
Closes https://github.com/AlphaWallet/alpha-wallet-ios/issues/1814

### CODE REVIEW

**Comment by hboon** [comment]
@vladyslav-iosdev is this for https://github.com/AlphaWallet/alpha-wallet-ios/issues/1814?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev is this for [AlphaWallet/alpha-wallet-ios#1814](https://github.com/AlphaWallet/alpha-wallet-ios/issues/1814)?

yep, i found on Bug, and fixed it

**Comment by hboon** [comment]
Can you describe the bug here and describe the bug/fix in the commit message? :)

**Comment by vladyslav-iosdev** [comment]
> Can you describe the bug here and describe the bug/fix in the commit message? :)

done :)

**Comment by hboon** [comment]
I see. Can you help include 2 (or more if you need) screenshots to show the before and after the PR so it’s easier to tell? (In the PR).

**Comment by vladyslav-iosdev** [comment]
**Before PR:**
IMG_0064
IMG_0063

**After PR:**
IMG_0066
IMG_0065

**Comment by hboon** [comment]
@vladyslav-iosdev for me to review?

**Review by hboon — APPROVED** [review]

**Review by hboon — CHANGES_REQUESTED** [review]
@vladyslav-iosdev looks good, but it looks like there would be conflicts merging into the `alphawallet` branch. Can you resolve those?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev looks good, but it looks like there would be conflicts merging into the `alphawallet` branch. Can you resolve those?

now should be ok.

**Comment by hboon** [comment]
@vladyslav-iosdev can you rebase instead of merge? :)

**Comment by hboon** [comment]
There are conflicts. Is it possible you did `rebase master`? We'll want `git rebase alphawallet` instead.

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev can you rebase instead of merge? :)

yes, just a sec

**Comment by vladyslav-iosdev** [comment]
After calling `git rebase alphawallet`, it tells `Current branch #1814 is up to date.`

**Comment by vladyslav-iosdev** [comment]
@hboon now it should be ok, do i need to squash commits?

**Comment by hboon** [comment]
> squash

@vladyslav-iosdev ah yes. Maybe just the newer 2 into 1 since the other appears to be for something different?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev ah yes. Maybe just the newer 2 into 1 since the other appears to be for something different?

ok

**Comment by vladyslav-iosdev** [comment]
@hboon done

**Review by hboon — APPROVED** [review]

**Comment by hboon** [comment]
@vladyslav-iosdev thanks! Can you help to update the `Podfile` in https://github.com/AlphaWallet/alpha-wallet-ios/pull/2037?

**Comment by vladyslav-iosdev** [comment]
> @vladyslav-iosdev thanks! Can you help to update the `Podfile` in [AlphaWallet/alpha-wallet-ios#2037](https://github.com/AlphaWallet/alpha-wallet-ios/pull/2037)?

@hboon Done.

**Pull request merged**
